PortfolioSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from portfolios.views import HomePageView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^portfolios/', include('portfolios.urls', namespace='portfolios')),
    url(r'^txn/', include('transactions.urls', namespace='transactions')),
    url(r'^sec/', include('securities.urls', namespace='securities')),
    #url(r'^quotes/', include('quotes.urls', namespace='quotes')),
    url(r'^benchmarks/', include('benchmarks.urls', namespace='benchmarks')),
    url(r'^todos/', include('todos.urls', namespace='todos')),
    url(r'^accounts/', include('users.urls', namespace='accounts')),
]

portfolios/urls.py
from django.conf.urls import url

from .views import PortfolioCreateView, PortfolioDetailView, PortfolioListView, \
    PortfolioUpdatePerfView, PortfolioHoldingUpdateView, PortfolioChartView


urlpatterns = [
    url(regex=r'^new/$',
        view=PortfolioCreateView.as_view(),
        name="new"),

    url(regex=r'^(?P<pk>[0-9]+)/detail/$',
        view=PortfolioDetailView.as_view(),
        name="detail"),

    url(regex=r'^list/$',
        view=PortfolioListView.as_view(),
        name="list"),

    url(regex=r'^(?P<pk>[0-9]+)/update_perf/$',
        view=PortfolioUpdatePerfView.as_view(),
        name="update_perf"),

    url(regex=r'^(?P<pk>[0-9]+)/update_hlds/$',
        view=PortfolioHoldingUpdateView.as_view(),
        name="update_hlds"),

    url(regex=r'^(?P<pk>[0-9]+)/chart/$',
        view=PortfolioChartView.as_view(),
        name="chart"),

]

todos/urls.py
from django.conf.urls import url

from .views import TodoCreateView, TodoUpdateView


urlpatterns = [
    url(regex=r'^create$',
        view=TodoCreateView.as_view(),
        name='create'),

    url(regex=r'^(?P<pk>[0-9]+)/detail$',
        view=TodoUpdateView.as_view(),
        name='update'),

]

transactions/urls.py
from django.conf.urls import url

from .views import TransactionDelView, TransactionUpdateView, TransactionCreateView, TransactionUploadView, TransactionCreateMultipleView


urlpatterns = [
    url(regex=r'^(?P<pk>\d+)/update$',
        view=TransactionUpdateView.as_view(),
        name="update"),

    url(regex=r'^(?P<pk>\d+)/del$',
        view=TransactionDelView.as_view(),
        name='del'),

    url(regex=r'^(?P<pk>\d+)/add$',
        view=TransactionCreateView.as_view(),
        name='add'),

    url(regex=r'^(?P<pk>\d+)/upload$',
        view=TransactionUploadView.as_view(),
        name='upload'),

    url(regex=r'^(?P<pk>\d+)/add_n',
        view=TransactionCreateMultipleView.as_view(),
        name='add_n'),
]

performances/models.py
import pandas as pd

from django.db import models

from portfolios.models import Portfolio
from securities.models import Security
from benchmarks.models import Benchmark
from core.types import PositiveDecimalField, DecimalField
from core.mixins import DateUtilMixin
from core.utils import last_business_day, to_business_timestamp
from core.exceptions import PortfolioException


class AppendEmptyDatabaseException(PortfolioException):
    pass


class Performance(models.Model):
    """Base model for store performance related data for securities, portfolios and benchmarks"""
    date = models.DateField()
    value = DecimalField(default=0)
    gain = DecimalField(default=0)
    cash_flow = DecimalField(default=0)

    class Meta:
        get_latest_by = 'date'
        abstract = True

    def calculate_gain(self):
        pass


class BenchmarkPerformance(Performance):
    benchmark = models.ForeignKey(Benchmark,
                                  on_delete=models.CASCADE,
                                  related_name='performance')
    pass


class PortPerfManager(models.Manager):
    def update(self, portfolio, end_date, append=False):
        performances = self.filter(portfolio=portfolio)
        if append and performances.count()>0:
            base_record = performances.latest()
            start_date = to_business_timestamp(base_record.date)+1
        elif portfolio.transactions.count() > 0:
            base_record = PortfolioPerformance(portfolio=portfolio, value=0)
            start_date = portfolio.transactions.earliest().datetime
        else:
            return

        for d in pd.date_range(start=start_date, end=end_date, freq='B'):
            pos = portfolio.position(d)
            cf = portfolio.cash_flow(d)
            if base_record.value > 0:
                gain = ((pos.total_value()-cf)/base_record.value-1)*100
            else:
                gain = 0

            new_record = PortfolioPerformance(
                portfolio=portfolio,
                date=d,
                value=pos.total_value(),
                cash_flow=cf,
                gain=gain,
            )
            new_record.save()
            base_record = new_record

    def remove_after(self, date):
        self.filter(date__gte=date).delete()


class PortfolioPerformance(Performance):
    portfolio = models.ForeignKey(Portfolio,
                                  on_delete=models.CASCADE,
                                  related_name='performance')
    objects = PortPerfManager()

    class Meta:
        unique_together = ('portfolio', 'date')
        get_latest_by = 'date'

    def __str__(self):
        return "{}@{}(value={}, cash flow={}, gain={:.3f}".format(self.portfolio.name, self.date, self.value,
                                                             self.cash_flow, self.gain)


class SecurityPerformance(Performance):
    security = models.ForeignKey(Security,
                                 on_delete=models.CASCADE,
                                 related_name='performance')
    pass

performances/views.py
from django.shortcuts import render

# Create your views here.

portfolio/views.py
import datetime

from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404

from .models import Portfolio


class HomePageView(ListView):
    model = Portfolio
    template_name = 'homepage.html'


class PortfolioCreateView(CreateView):
    model = Portfolio
    fields = ['name', 'description']
    template_name = 'portfolio/new_portfolio.html'


class PortfolioDetailView(DetailView):
    template_name = 'portfolio/portfolio_detail.html'
    model = Portfolio

    def get_context_data(self, **kwargs):
        context = super(PortfolioDetailView, self).get_context_data(**kwargs)
        portfolio = get_object_or_404(Portfolio, pk=self.kwargs['pk'])
        context['portfolio'] = portfolio
        context['transactions'] = portfolio.transactions()
        context['holdings'] = portfolio.holdings(datetime.datetime.now()).values()
        return context

portfolios/views.py
import datetime as dt
import pandas as pd
import json

from django.shortcuts import render
from django.views.generic import TemplateView, RedirectView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers

from .models import Portfolio, Holding
from core.mixins import PortfoliosMixin
from todos.models import Todo
from transactions.forms import TransactionsUploadForm
from core.utils import last_business_day


class HomePageView(LoginRequiredMixin, TemplateView):
    # todo figure out a way to test w/ and w/o login user
    template_name = 'homepage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todo'] = Todo
        return context


class PortfolioCreateView(CreateView):
    model = Portfolio
    fields = ['name', 'description', 'owner']
    template_name = 'portfolio/new_portfolio.html'


class PortfolioDetailView(TemplateView):
    template_name = 'portfolio/portfolio_detail.html'

    # todo add performance for this year, last year, last month
    # todo add performance chart
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        portfolio = get_object_or_404(Portfolio, pk=self.kwargs['pk'])

        # Updating quotes for just the securities held by the portfolio
        portfolio.update_quotes()
        Holding.update_all_values(portfolio)
        portfolio.update_performance()

        context['portfolio'] = portfolio
        context['transactions'] = portfolio.transactions.all()
        context['upload_form'] = TransactionsUploadForm(portfolios=portfolio)
        context['position'] = portfolio.position(date=last_business_day())
        context['performance'] = portfolio.performance.order_by('-date').all()[:10]
        context['summary'] = portfolio.performance_summary()
        return context


class PortfolioListView(ListView):
    model = Portfolio
    template_name = 'portfolio/portfolio_list.html'


class PortfolioUpdatePerfView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        portfolio = get_object_or_404(Portfolio, pk=kwargs['pk'])
        return portfolio.get_absolute_url()

    def get(self, request, *args, **kwargs):
        portfolio = get_object_or_404(Portfolio, pk=kwargs['pk'])
        portfolio.performance.all().delete()
        portfolio.update_performance()
        return super().get(request, *args, **kwargs)


class PortfolioHoldingUpdateView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        portfolio = get_object_or_404(Portfolio, pk=kwargs['pk'])
        return portfolio.get_absolute_url()

    def get(self, request, *args, **kwargs):
        portfolio = get_object_or_404(Portfolio, pk=kwargs['pk'])
        portfolio.remove_all_holdings()
        portfolio.update_holdings()
        return super().get(request, *args, **kwargs)


class PortfolioChartView(TemplateView):
    # todo make other data available for charts (benchmark, gain, etc.)
    # todo refactor chart js code to show multiple charts
    # todo clean up code for charts
    template_name = 'portfolio/portfolio_chart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        portfolio = get_object_or_404(Portfolio, pk=self.kwargs['pk'])
        values = []
        for p in portfolio.performance.order_by('date').filter(date__gt=dt.date(2016,1,1)).all():
            values.append({'date': p.date.isoformat(), 'value': float(p.value)})

        context['values'] = json.dumps(values)
        return context

templates/portfolio/_holdings.html
<div>
    <h4>
        Total Value: {{ position.total_value|floatformat:2 }}
    </h4>
    <ul>
        {{ position.sum_currency|unordered_list }}
    </ul>
</div>

<div>
    <table class="table table-striped" id="holding_table">
        <thead>
        <td>Name</td>
        <td>Symbol</td>
        <td>Currency</td>
        <td>Shares</td>
        <td>Cost</td>
        <td>Cost/s</td>
        <td>Value</td>
        <td>Dividend</td>
        <td>Gain</td>
        </thead>
        {% for hld in position %}
            <tr>{{ hld.as_t|safe }}</tr>
        {% endfor %}
    </table>
</div>

templates/portfolio/_performance.html
<table class="table table-striped" id="performance_table">
    <thead>
        <td>Date</td>
        <td>Value</td>
        <td>Cash Flow</td>
        <td>Gain</td>
    </thead>
    {% for item in performance %}
        <tr>
            <td>{{ item.date }}</td>
            <td>{{ item.value|floatformat:2 }}</td>
            <td>{{ item.cashflow|floatformat:2 }}</td>
            <td>{{ item.gain|floatformat:2 }}%</td>
        </tr>
    {% endfor %}
</table>

templates/portfolio/_performance_list.html
<table class="table table-striped" id="performance_list_table">
    <thead>
        <td>Date</td>
        <td>Value</td>
        <td>Cash Flow</td>
        <td>Gain</td>
    </thead>
    {% for item in performance %}
        <tr>
            <td>{{ item.date }}</td>
            <td>{{ item.value|floatformat:2 }}</td>
            <td>{{ item.cashflow|floatformat:2 }}</td>
            <td>{{ item.gain|floatformat:2 }}%</td>
        </tr>
    {% endfor %}
</table>

templates/portfolio/_performance_summary.html
{% load bench_extras %}

<table class="table table-striped" id="performance_summary_table">
    <thead>
        <td></td>
        <td>last week</td>
        <td>last year</td>
        <td>YTD</td>
    </thead>
    <tr>
        <td>TWRR</td>
        <td>{{ summary.twrr.last_week|percent }}</td>
        <td>{{ summary.twrr.last_year|percent }}</td>
        <td>{{ summary.twrr.ytd|percent }}</td>
    </tr>
    <tr>
        <td>MWRR</td>
        <td>{{ summary.mwrr.last_week|percent }}</td>
        <td>{{ summary.mwrr.last_year|percent }}</td>
        <td>{{ summary.mwrr.ytd|percent }}</td>
    </tr>
</table>

templates/portfolio/_portfolio_list.html
{% for ptf in portfolios %}
    <li><a href="{%  url 'portfolios:detail' ptf.id %}">{{ ptf.name }}</a></li>
{% endfor %}

templates/portfolio/new_portfolio.html
{% extends "__l_single_col.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>New Portfolio</h1>
    </div>

    {% include "includes/_form.html" %}

{% endblock content %}

templates/portfolio/portfolio_chart.html
{% extends "__l_single_col.html" %}
{% load static %}

{% block title %}
    Portfolio Chart
{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static "amcharts/style.css" %}" type="text/css" />
    <script src="{% static "amcharts/amcharts.js" %}"></script>
    <script src="{% static "amcharts/serial.js" %}"></script>
    <script src="{% static "amcharts/amstock.js" %}"></script>
    <script src="{% static "amcharts/plugins/dataloader/dataloader.min.js" %}" type="text/javascript"></script>
    <script type="text/javascript">
        AmCharts.ready(function() {
            var chartData = {{ values|safe }};

            var chart = new AmCharts.AmStockChart();
            chart.pathToImages = "{% static "amcharts/images/" %}";

            var dataSet = new AmCharts.DataSet();
            dataSet.dataProvider = chartData;
            dataSet.fieldMappings = [{fromField:"value", toField:"value"}];
            dataSet.categoryField = "date";
            chart.dataSets = [dataSet];

            var stockPanel = new AmCharts.StockPanel();
            chart.panels = [stockPanel];

            var panelsSettings = new AmCharts.PanelsSettings();
            panelsSettings.startDuration = 1;
            chart.panelsSettings = panelsSettings;

            var categoryAxesSettings = new AmCharts.CategoryAxesSettings();
            //categoryAxesSettings.minPeriod = "hh";
            categoryAxesSettings.equalSpacing = true;
            chart.categoryAxesSettings = categoryAxesSettings;

            var graph = new AmCharts.StockGraph();
            graph.valueField = "value";
            graph.type = "column";
            graph.fillAlphas = 1;
            graph.title = "Value";
            stockPanel.addStockGraph(graph);

            var chartScrollbarSettings = new AmCharts.ChartScrollbarSettings();
            chartScrollbarSettings.graph = graph;
            chartScrollbarSettings.graphType = "line";
            chart.chartScrollbarSettings = chartScrollbarSettings;

            var legend = new AmCharts.StockLegend();
            stockPanel.stockLegend = legend;

            var chartCursorSettings = new AmCharts.ChartCursorSettings();
            chartCursorSettings.valueBallonsEnabled = true;
            chart.chartCursorSettings = chartCursorSettings;

            var periodSelector = new AmCharts.PeriodSelector();
            periodSelector.periods = [
                {period:"DD", count:1, label:"1 day"},
                {period:"DD", count:5, label:"5 days"},
                {period:"MM", count:1, label:"1 month"},
                {period:"YYYY", count:1, selected:true, label:"1 year"},
                {period:"YTD", label:"YTD"},
                {period:"MAX", label:"MAX"}
            ];
            chart.periodSelector = periodSelector;

            chart.write("valuechartdiv");
        });
    </script>
{% endblock %}

{% block main_col %}
    <div id="valuechartdiv" style="width:100%; height:400px;"></div>
{% endblock %}

templates/portfolio/portfolio_detail.html
{% extends "__l_single_col.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Portfolio
{% endblock title %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static "bootstrap/css/fileinput.min.css" %}" type="text/css" />
    <script src="{% static "bootstrap/js/fileinput.min.js" %}"></script>
    <script src="{% static "js/portfolio_detail.js"%}"></script>
{% endblock %}

{% block main_col %}

    <div class="jumbotron">
        <h1>{{ portfolio.name }}</h1>
        <h2><i>{{ portfolio.description }}</i></h2>
        <a href="{% url 'portfolios:chart' portfolio.id %}">Chart</a>
    </div>

    <div class="row">
        <div class="page-header">
            <h3>Performance Summary</h3>
        </div>
        <div class="col-md-6">
            {% include 'portfolio/_performance_summary.html' %}
        </div>
    </div>

    <div class="row">
        <div class="page-header">
            <h3>Holdings</h3>
        </div>
        <div>
            <a href="{% url 'portfolios:update_hlds' portfolio.id %}"
               class="btn btn-default" role="button">Update</a>
        </div>
        <div>
            {% include 'portfolio/_holdings.html' %}
        </div>
    </div>

    <div class="row">
        <div class="page-header">
            <h3>Performance List</h3>
        </div>
        <div>
            <a href="{% url 'portfolios:update_perf' portfolio.id %}"
               class="btn btn-default" role="button">Update</a>
        </div>
        <div class="col-md-6">
            {% include 'portfolio/_performance_list.html' %}
        </div>
    </div>

    <div class="row">
        <div class="page-header">
            <h3>Transactions</h3>
        </div>
        <div class="col-md-1">
            <a href="{% url 'transactions:add' portfolio.id %}"
               class="btn btn-default" role="button">Add</a>
        </div>

        <div class="col-md-5">
            {% crispy upload_form upload_form.helper %}
        </div>

        <div>
            <table class="table table-striped" id="transaction_table">
                {% include "includes/_transaction_thead.html" %}
                {% for txn in transactions %}
                    {{ txn.as_t|safe }}
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock main_col %}

templates/portfolio/portfolio_list.html
{% extends "__l_single_col.html" %}

{% block title %}
    Portfolios
{% endblock title %}

{% block main_col %}
    {% include 'portfolio/_portfolio_list.html' with portfolios=object_list %}
{% endblock main_col %}