PortfolioSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from portfolios.views import HomePageView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^portfolios/', include('portfolios.urls', namespace='portfolios')),
    url(r'^txn/', include('transactions.urls', namespace='transactions')),
    url(r'^sec/', include('securities.urls', namespace='securities')),
    #url(r'^quotes/', include('quotes.urls', namespace='quotes')),
    url(r'^benchmarks/', include('benchmarks.urls', namespace='benchmarks')),
    url(r'^todos/', include('todos.urls', namespace='todos')),
    url(r'^accounts/', include('users.urls', namespace='accounts')),
]

benchmarks/urls.py
from django.conf.urls import url

from .views import BenchmarkCreateView, BenchmarkDetailView, BenchmarkListView
from .views import ConstituteCreateView, ConstituteDeleteView, ConstituteUpdateView, ConstituteNormalizeView

urlpatterns = [
    url(regex=r'^create$',
        view=BenchmarkCreateView.as_view(),
        name="create"),

    url(regex=r'^(?P<pk>[0-9]+)/detail$',
        view=BenchmarkDetailView.as_view(),
        name="detail"),

    url(regex=r'^list$',
        view=BenchmarkListView.as_view(),
        name="list"),

    url(regex=r'^(?P<pk>[0-9]+)/constitute/create$',
        view=ConstituteCreateView.as_view(),
        name="create-cst"),

    url(regex=r'^(?P<pk>[0-9]+)/constitute/delete$',
        view=ConstituteDeleteView.as_view(),
        name="delete-cst"),

    url(regex=r'^(?P<pk>[0-9]+)/constitute/update$',
        view=ConstituteUpdateView.as_view(),
        name="update-cst"),

    url(regex=r'^(?P<pk>[0-9]+)/constitute/normalize$',
        view=ConstituteNormalizeView.as_view(),
        name="normalize-cst"),

]

portfolios/urls.py
from django.conf.urls import url

from .views import PortfolioCreateView, PortfolioDetailView, PortfolioListView, \
    PortfolioUpdatePerfView, PortfolioHoldingUpdateView, PortfolioChartView


urlpatterns = [
    url(regex=r'^new/$',
        view=PortfolioCreateView.as_view(),
        name="new"),

    url(regex=r'^(?P<pk>[0-9]+)/detail/$',
        view=PortfolioDetailView.as_view(),
        name="detail"),

    url(regex=r'^list/$',
        view=PortfolioListView.as_view(),
        name="list"),

    url(regex=r'^(?P<pk>[0-9]+)/update_perf/$',
        view=PortfolioUpdatePerfView.as_view(),
        name="update_perf"),

    url(regex=r'^(?P<pk>[0-9]+)/update_hlds/$',
        view=PortfolioHoldingUpdateView.as_view(),
        name="update_hlds"),

    url(regex=r'^(?P<pk>[0-9]+)/chart/$',
        view=PortfolioChartView.as_view(),
        name="chart"),

]

todos/urls.py
from django.conf.urls import url

from .views import TodoCreateView, TodoUpdateView


urlpatterns = [
    url(regex=r'^create$',
        view=TodoCreateView.as_view(),
        name='create'),

    url(regex=r'^(?P<pk>[0-9]+)/detail$',
        view=TodoUpdateView.as_view(),
        name='update'),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

templates/includes/_form.html
{% load crispy_forms_tags %}

<form method="post" action="{% block form_action %}{% endblock %}">
    <div class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-default">{{ ok_text|default:"OK" }}</button>
    </div>
</form>

templates/includes/_jumbotron_header.html
<div class="jumbotron">
    <h1>{{ header }}</h1>
</div>

templates/includes/_navigation.html
<div class="container-fluid">
<nav class="navbar navbar-default">
    <div id="navbar" class="navbar-collapse collapse">
        <div class="navbar-header">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home' %}"><b>Filter</b></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Security
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'securities:new' %}">New</a></li>
                        <li><a href="{% url 'securities:list' %}?page=1">List All</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Portfolio
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'portfolios:new' %}">New</a></li>
                        <li><a href="{% url 'portfolios:list' %}">List All</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Benchmark
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'benchmarks:create' %}">Create</a></li>
                        <li><a href="{% url 'benchmarks:list' %}">List All</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Todo
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'todos:create' %}">Create</a></li>
                    </ul>
                </li>
            </ul>
        </div>

        <div class="nav navbar-right navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if user.id %}
                    <li><a href="#">{{ user }}</a></li>
                    <li><a href="{% url 'accounts:logout' %}?next=/">logout</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}?next=/">login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
</div>

templates/includes/_transaction_thead.html
<thead>
    <td>Type</td>
    <td>Date</td>
    <td>Name</td>
    <td>Symbol</td>
    <td>Shares</td>
    <td>Price</td>
    <td>Fee</td>
    <td>Cash Flow</td>
    <td>Dividend</td>
    <td>Ratio</td>
</thead>